### PR TITLE
change CONTRIBUTING.md to run Travis on forked repository

### PR DESCRIPTION
**Pull request by marutosi**
This is **normal** way of DVCS workflow.
https://github.com/opf/openproject/pull/1362#issuecomment-44685415

Travis tests of pull request does not run on central repository in this workflow.
So it reduces large times of Travis on central repository.

### CODE REVIEW

**Comment by floriank** [comment]
I do not understannd your problem. If you want to build the forked repo, I would suggest you do the following:

In your fork, on `dev`:
1. `git checkout -b marutosi-dev`
2. change `.travis.yml` all you like (I assume you want to build everything)
3. in the settings, connect TravisCI to build your repository
4. `git push --set-upstream origin marutosi-dev`

To work with that, assuming you want to build a feature:

1. (on `marutosi-dev`) `git checkout -b feature/interesting_new_feature`
2. work on your feature, add files, etc.
3. `git push --set-upstream origin feature/interesting_new_feature`
4. Travis will now build your feature branch

To create a PR against `opf/openproject`:

1. (on `feature/interesting_new_feature`) `git rebase dev` (I also suggest you pull the latest dev from `opf/openproject`)
2. You can now either delete the remote version of the feature branch or just force push to **your** repo
3. Create a PR against `dev` in `opf/openproject`

I know it's a little bit more cumbersome, but this should work and you can use Travis to build your branches all you want.

*Please refrain from opening the same PR over and over again.*

Also, if you force push against your PR, please stop associated builds, otherwise you block Travis for us.

Thanks!

**Comment by marutosi** [comment]
Travis does not run again if git hash id is same.
If one run on Travis and send pull request, GitHub simply refer Travis result on one's repository.
Above workflow changed git hash id.

**Comment by floriank** [comment]
you could still squash the commit in your feature branch and cherry pick it onto dev. You would have a different git commit hash.

**Comment by marutosi** [comment]
Do you understand?
I don't say such things.

**Comment by marutosi** [comment]
All commits run on forked repository Travis.
Do you understand?

**Comment by floriank** [comment]
I think I do.

But then again, I can just make suggestions for you to achieve a solution that works for you, as well as for us, as we will not include every branch of the `opf/openproject` to be build by Travis.

**Comment by marutosi** [comment]
Do you understand?

> we will not include every branch of the opf/openproject to be build by Travis.

My suggestion is it.

**Comment by marutosi** [comment]
Do you have experiences to send pull request for other popular projects?

**Comment by floriank** [comment]
No, i do not. 

However, I do understand your suggestion. Still, you have to acknowledge that we will not adapt your suggestion for reasons given beforehand. Also, the argument that "other popular projects do it" is invalid as it is an [argument from authority](http://en.wikipedia.org/wiki/Argument_from_authority).

**Comment by marutosi** [comment]
> "other popular projects do it"

All except OpenProject do it.

**Comment by floriank** [comment]
I doubt that you checked all of them.

In addition, you seem to suggest changes that benefit only you, disregarding the needs and opinions of the other contributors and collaborators (which have given you their reasons in the past), which, in itself is questionable to me.

**Comment by marutosi** [comment]
Do you understand?

> benefit only you

benefit for OpenProject too.

**Comment by marutosi** [comment]
> I doubt that you checked all of them.

I send pull request for many projects.

**Comment by floriank** [comment]
I see that you think this will be a benefit for OP and your concern is **highly appreciated**.

Again, there are reasons to stick to our own workflow *for now*.

As @myabc commented [here](https://github.com/opf/openproject/pull/1362#issuecomment-44742553), we are open to these suggestions and yes, we did hear you the first time this topic came up.

As @linki explained [here](https://github.com/opf/openproject/pull/1362#issuecomment-44685415), we will currently not build all branches.

However, I will bring this up at our next internal meeting so that your suggestion will stay in the loop.

**Comment by floriank** [comment]
In the meantime, please be sure that you were heard and we take you *very* seriously on the matter.

But please refrain from bringing it up constantly and creating the same PR over and over again.

Thanks!

In the meantime, enjoy a picture of one my cat:

img_20150202_025118

**Comment by floriank** [comment]
@marutosi I continue this discussion in the original PR over at the `opf/openproject` repo.

**Comment by marutosi** [comment]
> Travis does not run again if git hash id is same.

It seems travis behavior changed before 5 Mar 2014.
https://github.com/travis-ci/docs-travis-ci-com/blame/d8e0c6f40355a121aea788becc92fd336edb0ada/user/pull-requests.md#L24

**Comment by marutosi** [comment]
https://github.com/travis-ci/travis-ci/issues/1147

**Pull request closed without merging**
